// Generates all Momentum secrets and writes .env (gitignored). Prints the owner passphrase once.
// Usage: node scripts/gen-secrets.mjs [passphrase]
import { hash } from "@node-rs/argon2";
import webpush from "web-push";
import { randomBytes } from "node:crypto";
import { writeFileSync, existsSync, readFileSync } from "node:fs";

const b64 = (n) => randomBytes(n).toString("base64");
const b64url = (n) => randomBytes(n).toString("base64url");

const sessionSecret = b64url(32);
const fieldKey = b64(32);
const vapid = webpush.generateVAPIDKeys();
const passphrase = process.argv[2] || `mom-${b64url(12)}`;
const passHash = await hash(passphrase, { algorithm: 2, memoryCost: 65536, timeCost: 3, parallelism: 1 });

// Preserve an existing GEMINI_API_KEY if .env already has one.
let geminiKey = "";
if (existsSync(".env")) {
  const m = /^GEMINI_API_KEY=(.*)$/m.exec(readFileSync(".env", "utf8"));
  if (m) geminiKey = m[1].replace(/^"|"$/g, "");
}

const env = `# Generated by scripts/gen-secrets.mjs — DO NOT COMMIT
OWNER_EMAIL=divyamohan1993@gmail.com
OWNER_PASSPHRASE_HASH="${passHash.replace(/\$/g, "\\$")}"
SESSION_SECRET="${sessionSecret}"
FIELD_KEY="${fieldKey}"
EDGE_SECRET=
GEMINI_API_KEY=${geminiKey}
GEMINI_MODEL=gemini-2.5-flash
GEMINI_DAILY_CAP=200
VAPID_PUBLIC_KEY="${vapid.publicKey}"
VAPID_PRIVATE_KEY="${vapid.privateKey}"
VAPID_SUBJECT=mailto:divyamohan1993@gmail.com
GCP_PROJECT=dmjone
FIRESTORE_DATABASE=(default)
SWEEP_INVOKER_SA=
SWEEP_AUDIENCE=
TZ=Asia/Kolkata
NODE_ENV=development
`;
writeFileSync(".env", env);

// Raw values (unescaped) for Secret Manager provisioning.
writeFileSync(
  "secrets.json",
  JSON.stringify(
    {
      OWNER_PASSPHRASE_HASH: passHash,
      SESSION_SECRET: sessionSecret,
      FIELD_KEY: fieldKey,
      VAPID_PUBLIC_KEY: vapid.publicKey,
      VAPID_PRIVATE_KEY: vapid.privateKey,
    },
    null,
    2,
  ),
);

// Machine-readable summary for provisioning (no secrets logged beyond what the owner needs).
console.log(
  JSON.stringify(
    { passphrase, vapidPublic: vapid.publicKey, wroteEnv: true },
    null,
    2,
  ),
);
