// Generates Momentum encryption, CSRF and push secrets for a NEW installation.
// Never run this against an existing installation: FIELD_KEY protects existing data.
import webpush from "web-push";
import { randomBytes } from "node:crypto";
import { writeFileSync } from "node:fs";

const b64 = (n) => randomBytes(n).toString("base64");
const b64url = (n) => randomBytes(n).toString("base64url");

const sessionSecret = b64url(32);
const fieldKey = b64(32);
const vapid = webpush.generateVAPIDKeys();
const env = `# Generated by scripts/gen-secrets.mjs — DO NOT COMMIT
OWNER_EMAIL=divyamohan1993@gmail.com
OWNER_GOOGLE_UID=
OWNER_GOOGLE_SUB=
FIREBASE_API_KEY=
FIREBASE_APP_ID=
APP_ORIGIN=https://momentum.dmj.one
SESSION_SECRET="${sessionSecret}"
FIELD_KEY="${fieldKey}"
EDGE_SECRET=
VERTEX_LOCATION=global
GEMINI_MODEL=gemini-2.5-flash-lite
GEMINI_DAILY_CAP=200
VAPID_PUBLIC_KEY="${vapid.publicKey}"
VAPID_PRIVATE_KEY="${vapid.privateKey}"
VAPID_SUBJECT=mailto:divyamohan1993@gmail.com
GCP_PROJECT=dmjone
FIRESTORE_DATABASE=(default)
SWEEP_INVOKER_SA=
SWEEP_AUDIENCE=
TZ=Asia/Kolkata
NODE_ENV=development
`;
writeFileSync(".env", env);

// Raw values (unescaped) for Secret Manager provisioning.
writeFileSync(
  "secrets.json",
  JSON.stringify(
    {
      SESSION_SECRET: sessionSecret,
      FIELD_KEY: fieldKey,
      VAPID_PUBLIC_KEY: vapid.publicKey,
      VAPID_PRIVATE_KEY: vapid.privateKey,
    },
    null,
    2,
  ),
);

// Machine-readable summary for provisioning (no secrets logged beyond what the owner needs).
console.log(
  JSON.stringify(
    { vapidPublic: vapid.publicKey, wroteEnv: true },
    null,
    2,
  ),
);
